apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: {{ .Values.flask.port }}
    protocol: TCP
    name: http
  selector:
    app: flask
