apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.nginx.port }}
    protocol: TCP
    name: http
  selector:
    app: nginx
